CREATE PROCEDURE spCreateTitulo
    @Id UNIQUEIDENTIFIER,
    @Acao INT,
	@Aceite VARCHAR(20),
	@ApresentanteId UNIQUEIDENTIFIER,
	@CredorId UNIQUEIDENTIFIER,
	@DataAcao DATETIME,
	@DataEmissao DATETIME,
	@DataProtesto DATETIME,
	@DataProtocolo DATETIME,
	@DataVencimento DATETIME,
	@Endosso VARCHAR(20),
	@Especie VARCHAR(50),
	@FinsFalimentares TINYINT,
	@Folha INT,
	@Livro INT,
	@MotivoProtesto INT,
	@NossoNumero INT,
	@Numero INT,
	@NumeroProtesto INT,
	@Protocolo VARCHAR(100),
	@Saldo DECIMAL(18,0),
	@Sequencial INT,
	@Valor DECIMAL(18,0)
AS
    INSERT INTO [Titulo] (
        [Id], 
		[Acao],
		[Aceite],
		[ApresentanteId],
		[CredorId],
		[DataAcao],
		[DataEmissao],
		[DataProtesto],
		[DataProtocolo],
		[DataVencimento],
		[Endosso],
		[Especie],
		[FinsFalimentares],
		[Folha],
		[Livro],
		[MotivoProtesto],
		[NossoNumero],
		[Numero],
		[NumeroProtesto],
		[Protocolo],
		[Saldo],
		[Sequencial],
		[Valor]
    ) VALUES (
         @Id,
		 @Acao,
		 @Aceite,
		 @ApresentanteId,
		 @CredorId,
		 @DataAcao,
		 @DataEmissao,
		 @DataProtesto,
		 @DataProtocolo,
		 @DataVencimento,
		 @Endosso,
		 @Especie,
		 @FinsFalimentares,
		 @Folha,
		 @Livro,
		 @MotivoProtesto,
		 @NossoNumero,
		 @Numero,
		 @NumeroProtesto,
		 @Protocolo,
		 @Saldo,
		 @Sequencial,
		 @Valor
    )
