CREATE PROCEDURE spCreateCargaDiaria
    @TitId UNIQUEIDENTIFIER,
	@Tit_PesID UNIQUEIDENTIFIER,
	@Tit_AprId UNIQUEIDENTIFIER,
	@TitProtocolo VARCHAR(50),
	@TitDataProtocolo DATETIME,
	@TitLivro VARCHAR(20),
	@TitFolha VARCHAR(20),
	@TitDataProtesto DATETIME,
	@TitNumeroProtesto INT,
	@TitDataEmissao DATETIME,
	@TitDataVencimento DATETIME,
	@TitEspecie VARCHAR(20),
	@TitNumero INT,
	@TitNossoNumero VARCHAR(100),
	@TitValor DECIMAL(10, 2),
	@TitSaldo DECIMAL(10, 2),
	@TitEndosso VARCHAR(100),
	@TitAceite VARCHAR(20),
	@TitFinsFalimentares BIT,
	@TitMotivoProtesto VARCHAR(100),
	@TitAcao INT,
	@TitDataAcao DATETIME,
	@TitSequencial INT
AS
    INSERT INTO [CadCargaDiaria] (
    [TitId],
	[Tit_PesID],
	[Tit_AprId],
	[TitProtocolo],
	[TitDataProtocolo],
	[TitLivro],
	[TitFolha],
	[TitDataProtesto],
	[TitNumeroProtesto],
	[TitDataEmissao],
	[TitDataVencimento],
	[TitEspecie],
	[TitNumero],
	[TitNossoNumero],
	[TitValor],
	[TitSaldo],
	[TitEndosso],
	[TitAceite],
	[TitFinsFalimentares],
	[TitMotivoProtesto],
	[TitAcao],
	[TitDataAcao],
	[TitSequencial]
    ) VALUES (
    @TitId,
	@Tit_PesID,
	@Tit_AprId,
	@TitProtocolo,
	@TitDataProtocolo,
	@TitLivro,
	@TitFolha,
	@TitDataProtesto,
	@TitNumeroProtesto,
	@TitDataEmissao,
	@TitDataVencimento,
	@TitEspecie,
	@TitNumero,
	@TitNossoNumero,
	@TitValor,
	@TitSaldo,
	@TitEndosso,
	@TitAceite,
	@TitFinsFalimentares,
	@TitMotivoProtesto,
	@TitAcao,
	@TitDataAcao,
	@TitSequencial
    )
